// <auto-generated />
using Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(PhoneShopDataContext))]
    [Migration("20230214135347_CreatePhoneShopDatabase")]
    partial class CreatePhoneShopDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Business.Domain.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Apple"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Google"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Huawei"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Samsung"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Xiaomi"
                        });
                });

            modelBuilder.Entity("Business.Domain.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceNoVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("PhoneId");

                    b.HasIndex("BrandId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            BrandId = 1,
                            Description = "Met de dubbele camera schiet je in elke situatie een perfecte foto of video. De krachtige A13-chipset zorgt voor razendsnelle prestaties. Met Face ID hoef je enkel en alleen naar je toestel te kijken om te ontgrendelen. Het toestel heeft een lange accuduur dankzij een energiezuinige processor",
                            Model = "iPhone 11",
                            PriceNoVat = 0m,
                            PriceVat = 619m,
                            Stock = 5
                        },
                        new
                        {
                            PhoneId = 2,
                            BrandId = 2,
                            Description = "12.2 megapixel camera, 4k videokwaliteit 5.81 inch OLED scherm, 128 GB opslaggeheugen 3140 mAh accucapaciteit",
                            Model = "Pixel 4a",
                            PriceNoVat = 0m,
                            PriceVat = 411m,
                            Stock = 5
                        },
                        new
                        {
                            PhoneId = 3,
                            BrandId = 3,
                            Description = "6.47\" FHD+ (2340x1080) OLED, Kirin 980 Octa-Core (2x Cortex-A76 2.6GHz + 2x Cortex-A76 1.92GHz + 4x Cortex-A55 1.8GHz), 8GB RAM, 128GB ROM, 40+20+8+TOF/32MP, Dual SIM, 4200mAh, Android 9.0 + EMUI 9.1",
                            Model = "P30",
                            PriceNoVat = 0m,
                            PriceVat = 697m,
                            Stock = 5
                        },
                        new
                        {
                            PhoneId = 4,
                            BrandId = 4,
                            Description = "64 megapixel camera, 4k videokwaliteit 6.5 inch AMOLED scherm 128 GB opslaggeheugen (Uitbreidbaar met Micro-sd) Water- en stofbestendig (IP67)",
                            Model = "Galaxy A52",
                            PriceNoVat = 0m,
                            PriceVat = 399m,
                            Stock = 5
                        },
                        new
                        {
                            PhoneId = 5,
                            BrandId = 5,
                            Description = "108 megapixel camera, 4k videokwaliteit 6.67 inch AMOLED scherm, 128 GB opslaggeheugen (Uitbreidbaar met Micro-sd). Water- en stofbestendig (IP53)",
                            Model = "Xiaomi",
                            PriceNoVat = 0m,
                            PriceVat = 298m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("Business.Domain.Models.Phone", b =>
                {
                    b.HasOne("Business.Domain.Models.Brand", "Brand")
                        .WithMany("Phones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Business.Domain.Models.Brand", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
